### ISSUE TITLE
Request for Examples on Usage

### ISSUE THREAD

**Issue by fahimfarhan** [nickwbarber/HILT-annotations#1]
Hello @nickwbarber , could you provide me with some examples on how to use "gatenlp" ? I'm working on a project. My teacher wants me to use GATE Developer. However, I need to use python as well. Your project seems promising. But I really could not understand the documentation. Help :(

**Comment by nickwbarber** [comment]
Hi @fahimfarhan. Some scripts I've written which use this package can be found at github.com/nickwbarber/hilt-scripts. Pay more attention to the more recently edited ones, since they are more likely to be representative of the current version of gatenlp's usage.

FYI: I have no plans to continue developing this package, but I'm sure I could find some time to help clarify specific questions of yours that might come up.
